### PR TITLE
Ft landing page 163348587

### PR DESCRIPTION
**Pull request by Fiyiin**
### What does this PR do?
- This PR adds the index page and the sign in modal form to the application.

### How should this be manually tested?
- Visit https://fiyiin.github.io/politico/ui/index.html
- The index page(landing page) will be displayed to you
- Click on the login link
- The modal form for the login will be displayed to you

#### Any background context you want to provide
- The landing page is the first page that gets displayed when a user visits the app, It contains links to the other pages 

#### What are the relevant Pivotal Tracker Stories
- Story id: #163348587

#### Questions
- None

in

landing

### CODE REVIEW

**Comment by Felglitzzz** [comment]
@Fiyiin 
- Nice work, thus far
- Your landing page has a default `current` marker on the `signup` button even though it is not on the signup page but rather on the landing page
- Can you explain to me what `pricing` and `features` navs will accomplish in the politico app
- Your call to action buttons are not working.
- The text size for the voting services section and downwards is too big
- I am not sure the signup title and the call to action button close to the footer is supposed to be there. And if it is supposed to be there for any reason, it is not properly aligned
- Try to differentiate the footer from the rest page

**Comment by Fiyiin** [comment]
@Felglitzzz 

- I don't understand your first point
- ```pricing```  and ```features``` were a mistake I've changed it to ```services``` and ```about```
- Fixed the call to actions
- Adjusted the text sizes
- I wanted to that sign up and CTA to act as a visual break, the design is proving tricky. I've removed 
  that section.
- Fixed the footer.

**Comment by Felglitzzz** [comment]
@Fiyiin 
- the sign-up nav is highlighted on the landing page. Is that supposed to be the normal behaviour?
- kindly update the PR image(s)
- I can't go back to the landing page from the signup page if I choose not to sign up
- For the footer, the font colour u used was fine, what I mean is there should be some form of demarcation like the one we currently have on `GitHub site`or slightly different background colour

**Comment by Felglitzzz** [comment]
@Fiyiin , make all the pages responsive

**Comment by Fiyiin** [comment]
@Felglitzzz 

- Yes, the signup nav should be highlighted
- Updated the PR images
- I put a footer in the signup page (the footer still has some issues)
- I changed the design for the footer, for responsiveness
- Made the pages responsive

smallin
smallup
res1
res2

**Pull request merged**
